---
title: "Maps1"
author: "Jamie Zhang"
date: "2025-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)

map<-map_data("world")

ggplot(map,aes(x=long,y=lat,group=group))+
  geom_polygon(fill="darkslategrey",color="white")+
  theme_void()

North_Asia<-c("China","Japan","Mongolia","North Korea","South Korea","Taiwan")
North_Asia_map<-map_data("world",region=North_Asia)

ggplot(North_Asia_map,aes(x=long,y=lat,group=group))+
  geom_polygon(fill="springgreen",color="white")+
  theme_void()

region.data<-North_Asia_map%>%
  group_by(region) %>%
  summarise(long=mean(long),lat=mean(lat)) %>%
  arrange()

ggplot(North_Asia_map,
       aes(x=long,y=lat))+
  geom_polygon(aes(group=group,fill=region))+
  geom_text(data = region.data, aes(label = region),
            size = 3, hjust = 0.5, col = "red",
            fontface = "bold")+
  scale_fill_viridis_d()+
  theme_void()+
  theme(legend.position = "none")

drinks <- read_csv("drinks.csv")

drinks_maps <- drinks %>%
  left_join(map,by = c("country"="region"))

ggplot(drinks_maps,
       aes(long,lat,group=group))+
  geom_polygon(aes(fill=total_litres_of_pure_alcohol),
               color = "white")+
  scale_fill_viridis_c(option = "C")+
  labs(fill = "Total Liters of Pure Alcohol")+
  theme_void()+
  theme(legend.position = "bottom")


p<-ggplot(US_map, aes(x=long,y=lat))+
  geom_polygon(aes(group=group,fill = region),
               color = "white")+
  geom_text(data=state_data,aes(label = region.abb),
            fontface = "bold") +
  theme_void()+
  theme(legend.position = "none")

library(plotly)
ggplotly(p)

US_map <- map_data("state")
state_data <- US_map %>%
  filter(region != "district of columbia") %>%
  group_by(region) %>%
  summarize(long=mean(long),lat=mean(lat))%>%
  arrange(region)

state_data$region.abb <- state.abb[-c(2,11)]

crimes<-data.frame(region = rownames(USArrests),USArrests) %>%
  filter(region!=c("Alaska","Hawaii"))

crimes$regions<-tolower(crimes$region)

crimes_map<-crimes%>%
  left_join(US_map,by = "region")

g1 <- ggplot(crimes_map,aes(x = long,y = lat))+
  geom_polygon(aes(group = group,fill = Murder,
                   text = paste0(region,":\n",
                                 Murder, "murder arrests per 100,000"),
                   colour = "white"))+
  geom_text(data = state_data,
            aes(label = region.abb),fontface = "bold", size = 3)+
  scale_fill_viridis_c(option = "C") +
  theme_void()

ggplotly(g1,tooltip = "text")

covid <- read_csv("./COVID19.csv")

ohio <- covid %>%
  filter(administrative_area_level_2=="Ohio",
         date == "2021-12-31")

ohio_county <- map_data("county",region="ohio")

ohio_county$subregion<-str_to_title(ohio_county$subregion)

ohio_map <- ohio %>%
  left_join(ohio_county,
            by = c("county" = "subregion"))

g2 <- ggplot(ohio_map,
             aes(x = long, y = lat))+
  geom_polygon(aes(group = group, fill = deaths,
                   text = paste0("County: ", county, "\n",
                                 "Total Deaths: ", deaths)))+
  geom_text(data = ohio,
            aes(x = longitude, y = latitude, label = county),
            color = "white", fontface = "bold")+
  scale_fill_viridis_c(option = "H")+
  theme_minimal()+
  theme_void()

font <- list(
  family = "Arial",
  size = 15,
  color = "white"
)

label <- list(
  bgcolor = "#243F34",
  bordercolor = "transparent",
  font = font
)

ggplotly(g2,
         tooptip = "text",
         width = 850, height = 800) %>%
  style(hoverlabel = label) %>%
  layout(font = font)

```





